development:
  adapter: postgresql
  encoding: unicode
  database: PostEditor
  pool: 5
  username: PostEditorSuperUser
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: PostEditor
  pool: 5
  username: PostEditorSuperUser
  password: admin

production:
  adapter: postgresql
  database: PostEditor
  prepared_statements: false
  advisory_locks: false
  username: PostEditorSuperUser
  password: admin
