development:
  adapter: postgresql
  encoding: unicode
  database: PostEditor
  pool: 5
  username: PostEditorSuperUser
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: PostEditor
  pool: 5
  username: PostEditorSuperUser
  password: admin

production:
  adapter: postgresql
  database: deq72far5f1jbo
  prepared_statements: false
  advisory_locks: false
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
