development:
  adapter: postgresql
  encoding: unicode
  database: post_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: post_test
  pool: 5

production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
